'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const http = require('node:http');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

function listen(server) { return new Promise((resolve) => server.listen(0, '127.0.0.1', () => resolve(server.address().port))); }
function health(port) { return new Promise((resolve, reject) => { http.get({ hostname: '127.0.0.1', port, path: '/healthz' }, res => { let b=''; res.on('data', c => b += c); res.on('end', () => resolve(JSON.parse(b))); }).on('error', reject); }); }
function request(port, body) { return new Promise((resolve, reject) => { const r=http.request({hostname:'127.0.0.1',port,path:'/v1/chat/completions',method:'POST',headers:{'content-type':'application/json'}},res=>{let b='';res.on('data',c=>b+=c);res.on('end',()=>resolve({status:res.statusCode,body:b,headers:res.headers}));});r.on('error',reject);r.end(JSON.stringify(body)); }); }
function abortRequest(port, body) { return new Promise((resolve) => { const r=http.request({hostname:'127.0.0.1',port,path:'/v1/chat/completions',method:'POST',headers:{'content-type':'application/json'}},res=>{res.once('data',()=>r.destroy());res.once('close',resolve);});r.once('error',resolve);r.end(JSON.stringify(body)); }); }
async function spawnProxy({backend, enabled}) { const home=fs.mkdtempSync(path.join(os.tmpdir(),'gpt-oauth-test-')); fs.mkdirSync(path.join(home,'.zcode','gpt-oauth'),{recursive:true}); fs.writeFileSync(path.join(home,'.zcode','gpt-oauth','auth.json'),JSON.stringify({access:'fixture',refresh:'fixture',expires:Date.now()+3600000})); const probe=http.createServer(); const port=await listen(probe); await new Promise(r=>probe.close(r)); const child=spawn(process.execPath,[path.join(__dirname,'..','server','server.js'),'--http-only'],{env:{...process.env,NODE_ENV:'test',HOME:home,GPT_OAUTH_HOME:home,GPT_OAUTH_PROXY_PORT:String(port),GPT_OAUTH_BACKEND_BASE:`http://127.0.0.1:${backend}`,GPT_OAUTH_CACHE_MISS_NOTICES:enabled?'1':'0'},stdio:['ignore','ignore','pipe']}); return {child,home,port,ready:new Promise((resolve,reject)=>{let s='';const t=setTimeout(()=>reject(new Error('proxy start timeout '+s)),5000);child.stderr.on('data',d=>{s+=d;if(s.includes('Proxy listening')){clearTimeout(t);resolve(port);}});child.on('exit',c=>{if(c)reject(new Error('proxy exited '+c));});})}; }
function upstreamFixture() { let calls=0, requests=[]; const server=http.createServer((req,res)=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{requests.push(JSON.parse(b));calls++; if(requests.at(-1).model==='error'){res.writeHead(500,{'content-type':'application/json'});return res.end(JSON.stringify({error:{message:'fixture failure'}}));} const miss=0; const events=[{type:'response.output_text.delta',delta:'hello '},{type:'response.output_item.added',item:{type:'function_call',call_id:'call-1',name:'f'}},{type:'response.function_call_arguments.delta',item:{call_id:'call-1'},delta:'{}'},{type:'response.output_item.done',item:{type:'function_call',call_id:'call-1',name:'f',arguments:'{}'}},{type:'response.completed',response:{usage:{input_tokens:30000,output_tokens:2,input_tokens_details:{cached_tokens:miss}}}}];res.writeHead(200,{'content-type':'text/event-stream'});for(const [i,e] of events.entries()){const payload=JSON.stringify(e); if(i===0)res.write('data: '+payload.slice(0,8)+'\r\n'); else res.write('data: '+payload+'\r\n\r\n');}res.end('data: [DONE]\r\n\r\n');});}); return {server,requests}; }

let fixture, backendPort, proxy;
test.before(async()=>{fixture=upstreamFixture();backendPort=await listen(fixture.server);proxy=await spawnProxy({backend:backendPort,enabled:true});proxy.port=await proxy.ready;});
test.after(()=>{proxy.child.kill('SIGTERM');fixture.server.close();});

test('healthz reports effective cache setting', async()=>{ const h = await health(proxy.port); assert.equal(h.cacheMissNotices, true); });

test('enabled sequential nonstream emits usage then notice and strips metadata',{ concurrency: false },async()=>{let r=await request(proxy.port,{model:'gpt-5.6-sol',messages:[{role:'user',content:'x'}],cache_control:{session_id:'s',lineage_id:'l'}});assert.equal(r.status,200);const one=JSON.parse(r.body);assert.ok(one.cache_usage);assert.equal(one.cache_notice,undefined);r=await request(proxy.port,{model:'gpt-5.6-sol',messages:[{role:'user',content:'next'}],cache_control:{session_id:'s',lineage_id:'l'}});const two=JSON.parse(r.body);assert.ok(two.cache_notice);assert.ok(two.cache_usage.uncachedInputTokens||two.cache_usage.uncached_input_tokens);assert.equal('cache_control' in fixture.requests[0],false);});
test('stream preserves text/tool order and terminal metadata precedes done',async()=>{const r=await request(proxy.port,{stream:true,model:'gpt-5.6-sol',messages:[{role:'user',content:'x'}],cache_control:{session_id:'stream',lineage_id:'l'}});const chunks=r.body.split('\n\n').filter(Boolean);const done=chunks.findIndex(x=>x.includes('[DONE]'));assert.ok(done>0);const terminal=chunks[done-1];assert.match(terminal,/cache_usage|cache_notice/);assert.ok(chunks.findIndex(x=>x.includes('hello'))<chunks.findIndex(x=>x.includes('tool_calls')));});
test('upstream error does not commit baseline',async()=>{await request(proxy.port,{model:'error',messages:[],cache_control:{session_id:'err',lineage_id:'l'}});const r=await request(proxy.port,{model:'gpt-5.6-sol',messages:[],cache_control:{session_id:'err',lineage_id:'l'}});assert.equal(JSON.parse(r.body).cache_notice,undefined);});

test('proxy disconnect cancels in-flight baseline',async()=>{await abortRequest(proxy.port,{stream:true,model:'gpt-5.6-sol',messages:[],cache_control:{session_id:'disconnect',lineage_id:'l'}});await new Promise(r=>setTimeout(r,50));const r=await request(proxy.port,{model:'gpt-5.6-sol',messages:[],cache_control:{session_id:'disconnect',lineage_id:'l'}});assert.equal(JSON.parse(r.body).cache_notice,undefined);});

test('disabled proxy has no extensions and strips metadata',async()=>{const p=await spawnProxy({backend:backendPort,enabled:false});const port=await p.ready;const r=await request(port,{model:'gpt-5.6-sol',messages:[],cache_control:{session_id:'disabled',lineage_id:'l'}});const j=JSON.parse(r.body);assert.equal(j.cache_usage,undefined);assert.equal(j.cache_notice,undefined);p.child.kill('SIGTERM');});
