'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const {createTracker}=require('../server/cache/detector'); const {metric}=require('../server/cache/usage');
function u(input,read,time,model='m'){return {provider:'deepseek',model,sessionId:'s',lineageId:'l',observedAtMs:time,inputTokens:metric(input,'reported','x'),cacheReadTokens:read==null?null:metric(read,'reported','x'),cacheMissTokens:null,cacheTelemetry:'supported'};}
test('first request and noise produce no notice',()=>{const t=createTracker(); assert.equal(t.observe(u(30000,30000,1),{cacheMissNotices:true}),null); const d=t.observe(u(30000,28975,2),{cacheMissNotices:true}); assert.equal(d.significant,false); assert.equal(d.missedTokens.value,1025);});
test('significant overlap miss and model switch',()=>{const t=createTracker(); t.observe(u(40000,40000,1),{cacheMissNotices:true}); const d=t.observe(u(40000,10000,3,'n'),{cacheMissNotices:true}); assert.equal(d.missedTokens.value,30000); assert.equal(d.modelChanged,true);});
test('provider/session isolation',()=>{const t=createTracker(); const x=u(40000,40000,1); t.observe(x,{cacheMissNotices:true}); assert.equal(t.observe({...x,provider:'openai',cacheReadTokens:metric(0,'reported','x')},{cacheMissNotices:true}),null);});
test('begin/complete ignores reverse completion and reset stores baseline',()=>{const t=createTracker(); const a=u(40000,40000,1), b=u(40000,10000,2); const ta=t.begin(a,{cacheMissNotices:true}), tb=t.begin(b,{cacheMissNotices:true}); assert.equal(t.complete(ta),null); assert.equal(t.complete(tb),null); const c=u(40000,10000,3); const d=t.observe(c,{cacheMissNotices:true,reset:true}); assert.equal(d,null); assert.equal(t.observe(u(40000,0,4),{cacheMissNotices:true}).missedTokens.value,40000);});
test('capability changes disable model-switch comparison',()=>{const t=createTracker(); const a=u(40000,40000,1); a.capabilityId='a'; const b=u(40000,0,2,'new'); b.capabilityId='b'; t.observe(a,{cacheMissNotices:true}); assert.equal(t.observe(b,{cacheMissNotices:true}),null);});
test('in-flight generations obey maxEntries and evicted tokens are stale',()=>{const t=createTracker({maxEntries:10}); const tokens=[]; for(let i=0;i<100;i++){const x={...u(40000,40000,i),sessionId:'s'+i}; tokens.push(t.begin(x));} assert.ok(t.records.size<=10); assert.equal(t.preview(tokens[0],u(40000,0,101)),null); assert.equal(t.commit(tokens[0],u(40000,0,101)),null);});
test('cancel current generation preserves a prior baseline',()=>{const t=createTracker(); const baseline=u(40000,40000,1); t.observe(baseline,{cacheMissNotices:true}); const token=t.begin(u(40000,30000,2),{cacheMissNotices:true}); assert.equal(t.cancel(token),true); const d=t.observe(u(40000,0,3),{cacheMissNotices:true}); assert.equal(d.missedTokens.value,40000);});
test('reset followed by cancel cannot restore the pre-reset baseline',()=>{const t=createTracker(); const baseline=u(40000,40000,1); t.observe(baseline,{cacheMissNotices:true}); const token=t.begin(u(40000,30000,2),{cacheMissNotices:true,reset:true}); assert.equal(t.cancel(token),true); assert.equal(t.observe(u(40000,0,3),{cacheMissNotices:true}),null);});
test('ttl purge removes stale in-flight generations',()=>{const t=createTracker({ttlMs:1}); const token=t.begin(u(40000,40000,1)); const original=Date.now; Date.now=()=>token.begunAtMs+2; try{t.begin({...u(40000,40000,2),sessionId:'other'});}finally{Date.now=original;} assert.equal(t.records.has(token.id),false); assert.equal(t.preview(token,u(40000,0,3)),null);});
